language: python
python:
  - "3.8"
os: linux

env:
  global:
  - PGVER=12
  - PGPORT=5433
  - PGUSER=travis

services:
  - postgresql

addons:
  postgresql: "12"
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
      - postgresql-server-dev-12
      - postgresql-client-common
      - postgresql-common

before_install:
  - sudo sed -i -e "/local.*peer/s/postgres/all/" -e "s/peer\|md5/trust/g" /etc/postgresql/*/main/pg_hba.conf
  - postgres --version
  - sudo pg_ctlcluster 12 main restart

install:
  - pip install -r requirements.txt
  - pip install black
  - pip install flake8
  - pip install coverage
  - pip install pyyaml
  - pip install coveralls

before_script:
  - psql -c 'create database rrtestdb;' -U travis
  - python manage.py makemigrations
  - python manage.py makemigrations rrapp
  - python manage.py migrate auth
  - python manage.py migrate --run-syncdb
  - python manage.py migrate
  - black .


script:
  - black --check . --skip-string-normalization --exclude settings* --extend-exclude migrations*
  - flake8 .
  - coverage run --source=rrapp manage.py test --settings=roomierendezvous.settings


after_script:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: $AWS_REGION
  app: $AWS_APP_NAME
  env: $AWS_ENV_NAME
  bucket_name: $AWS_BUCKET_NAME
  on:
    branch: develop

after_deploy:
  - ./scripts/after_deploy_1.sh
